"""add assigned_room_id to staff

Revision ID: b6beee759d83
Revises: 8bf6be050c59
Create Date: 2026-09-11 18:09:07.273275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6beee759d83'
down_revision: Union[str, Sequence[str], None] = '8bf6be050c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('assigned_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_staff_assigned_room_id', 'staff', 'rooms', ['assigned_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_staff_assigned_room_id', 'staff', type_='foreignkey')
    op.drop_column('staff', 'assigned_room_id')
    # ### end Alembic commands ###
