import React, { useState, useMemo } from 'react';
import { useHotel } from '../../context/HotelContext';
import { PriorityBadge, StatusPill, StaffAvatar } from '../common/UIComponents';
import { ListTodo, Search, CheckCircle2, Clock, Filter, AlertCircle } from 'lucide-react';

export default function TasksView() {
  const { tasks, completeTask, loading } = useHotel();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('ALL');

  const filteredTasks = useMemo(() => {
    return tasks.filter((t) => {
      const matchSearch =
        String(t.room_id).includes(searchTerm) ||
        String(t.id).toLowerCase().includes(searchTerm.toLowerCase()) ||
        String(t.task_type).toLowerCase().includes(searchTerm.toLowerCase());
      const matchStatus = statusFilter === 'ALL' || t.status === statusFilter;
      return matchSearch && matchStatus;
    });
  }, [tasks, searchTerm, statusFilter]);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-gray-900 flex items-center gap-2">
            <ListTodo className="text-[#ff385c]" size={22} /> Operational Tasks Board
          </h2>
          <p className="text-xs text-gray-500 mt-1">
            Live PostgreSQL Tasks Generated by Autonomous Hotel Agents ({filteredTasks.length} Tasks)
          </p>
        </div>

        {/* Search */}
        <div className="relative w-full md:w-72">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
          <input
            type="text"
            placeholder="Search task ID, room, type..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 text-xs font-medium bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-rose-500"
          />
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1 text-xs font-semibold">
        {['ALL', 'PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED'].map((st) => (
          <button
            key={st}
            onClick={() => setStatusFilter(st)}
            className={`px-3.5 py-2 rounded-xl transition-all whitespace-nowrap ${
              statusFilter === st
                ? 'bg-neutral-900 text-white font-bold shadow-xs'
                : 'bg-white text-gray-600 hover:bg-gray-100 border border-gray-100'
            }`}
          >
            {st === 'ALL' ? 'All Tasks' : st.replace('_', ' ')}
          </button>
        ))}
      </div>

      {/* Data Table Container */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-xs overflow-hidden">
        {loading ? (
          <div className="text-center py-12 text-gray-400 text-xs">Loading operational tasks...</div>
        ) : filteredTasks.length === 0 ? (
          <div className="text-center py-12 text-gray-400 space-y-2">
            <CheckCircle2 size={36} className="mx-auto text-emerald-500 opacity-80" />
            <p className="text-sm font-semibold text-gray-700">No Operational Tasks Found</p>
            <p className="text-xs text-gray-400">Trigger a checkout event or maintenance report to generate tasks.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-gray-50/80 border-b border-gray-100 font-bold text-gray-500 uppercase tracking-wider text-[10px]">
                <tr>
                  <th className="py-3.5 px-4">Task ID</th>
                  <th className="py-3.5 px-4">Room</th>
                  <th className="py-3.5 px-4">Task Type</th>
                  <th className="py-3.5 px-4">Priority Level</th>
                  <th className="py-3.5 px-4">Status</th>
                  <th className="py-3.5 px-4">Assigned Staff</th>
                  <th className="py-3.5 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 font-medium text-gray-800">
                {filteredTasks.map((t) => (
                  <tr key={t.id} className="hover:bg-gray-50/60 transition-colors">
                    <td className="py-3.5 px-4 font-mono font-bold text-gray-900">{String(t.id).substring(0, 8)}</td>
                    <td className="py-3.5 px-4">
                      <span className="font-extrabold text-sm text-gray-900">Room {t.room_id}</span>
                    </td>
                    <td className="py-3.5 px-4">
                      <span className="font-semibold text-gray-700">{t.task_type}</span>
                    </td>
                    <td className="py-3.5 px-4">
                      <PriorityBadge level={t.priority_level} score={t.priority_score} />
                    </td>
                    <td className="py-3.5 px-4">
                      <StatusPill status={t.status} />
                    </td>
                    <td className="py-3.5 px-4">
                      {t.assigned_staff_id ? (
                        <span className="font-bold text-gray-900">Staff #{t.assigned_staff_id}</span>
                      ) : (
                        <span className="text-gray-400 italic">Unassigned</span>
                      )}
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      {t.status !== 'COMPLETED' ? (
                        <button
                          onClick={() => completeTask(t.id)}
                          className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-lg transition-all shadow-xs active:scale-95"
                        >
                          Complete Task
                        </button>
                      ) : (
                        <span className="text-emerald-600 font-bold flex items-center justify-end gap-1 text-xs">
                          <CheckCircle2 size={14} /> Done
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
